variables:
  ImageRepo: $CI_REGISTRY/no-fuss-computing/infrastructure/glpi/9.2.1
  ImageTag: latest
  GLPI_CLONE_FOLDER: glpi/glpi
  GLPI_APP_NAME: glpi
  GLPI_APP_CLONE_URL: https://github.com/glpi-project/glpi.git
  GLPI_APP_GIT_TAG: 9.2.1
    
stages:
  - prepare
  - build
  - staging
  - deploy
  - clean

prepare:Apps:
  stage: prepare
  before_script:
    - rm -fR $GLPI_APP_NAME/$GLPI_APP_NAME
    - git config --global http.sslVerify "false"
  script:
    - git clone --branch $GLPI_APP_GIT_TAG --depth 1 $GLPI_APP_CLONE_URL $GLPI_APP_NAME/$GLPI_APP_NAME
  artifacts:
    name: $APP_GIT_TAG
    expire_in: 1h
    paths:
      - $GLPI_APP_NAME/Dockerfile
      - $GLPI_APP_NAME/.dockerignore
      - $GLPI_APP_NAME/$GLPI_APP_NAME/*


build:App:
  stage: build
  image: gitlab/dind
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker info
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build $CI_PROJECT_DIR/$GLPI_APP_NAME/. --tag $ImageRepo:$GLPI_APP_GIT_TAG
    - docker push $ImageRepo:$GLPI_APP_GIT_TAG
  after_script:
    - docker logout $CI_REGISTRY
  tags:
   - docker
