INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Docker GLPI
repo_url: https://gitlab.com/nofusscomputing/projects/docker-glpi
edit_uri: '/-/ide/project/nofusscomputing/projects/docker-glpi/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - GLPI Docker:

    - projects/glpi/index.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

